---
title: "Application of BactDating on S. aureus ST239"
author: "Xavier Didelot"
date: '`r Sys.Date()`'
output:
  pdf_document: default
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{Application of BactDating on S. aureus ST239}
  %\usepackage[utf8]{inputenc}
---

In this vignette we demonstrate the usage of BactDating on a dataset of
Staphylococcus aureus ST239 published by Harris et al (2010).

##Initialisation

```{r}
library(BactDating)
library(ape)
set.seed(0)
data(staph)
plot(staph$tree, show.tip.label = F)
axisPhylo(backward = F)
```

##Root-to-tip analysis

Let's do a root-to-tip regression analysis:

```{r}
res=roottotip(staph$tree,staph$dates)
```

##Analysis

We run BactDating as follows:

```{r}
res=bactdate(unroot(staph$tree),staph$dates,nbIts=1e4)
plot(res,'treeCI',show.tip.label = F)
```

We can see what the MCMC traces look like:

```{r}
  plot(res,'trace')
```

Let's see where the root is likely to be:

```{r}
plot(res,'treeRoot',show.tip.label=F)
```
