# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coalpriorC <- function(leaves, nodes, alpha) {
    .Call('_BactDating_coalpriorC', PACKAGE = 'BactDating', leaves, nodes, alpha)
}

likelihoodGammaC <- function(tab, rate) {
    .Call('_BactDating_likelihoodGammaC', PACKAGE = 'BactDating', tab, rate)
}

likelihoodRelaxedgammaC <- function(tab, rate, ratestd) {
    .Call('_BactDating_likelihoodRelaxedgammaC', PACKAGE = 'BactDating', tab, rate, ratestd)
}

likelihoodPoissonC <- function(tab, rate) {
    .Call('_BactDating_likelihoodPoissonC', PACKAGE = 'BactDating', tab, rate)
}

changeinorderedvec <- function(vec, old, n) {
    invisible(.Call('_BactDating_changeinorderedvec', PACKAGE = 'BactDating', vec, old, n))
}

